"use client";
import { useCallback, useEffect, useState } from "react";
import {
  Braces,
  Check,
  ChevronRight,
  CircleAlert,
  GitBranch,
  Layers,
  LayoutDashboard,
  LoaderCircle,
  Network,
  Radio,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Workflow,
  X,
} from "lucide-react";
import { Button } from "./ui/button";
import { api, IncidentTable } from "./evidence-ui";
import { Overview } from "./overview";
import {
  Pipelines,
  Repositories,
  Runtime,
  Services,
  WorkspaceSettings,
} from "./data-pages";
import { Analyst, Investigation } from "./investigation";
import type { IncidentDetail, WorkspaceData } from "@/lib/types";
const navigation = [
  { name: "Overview", icon: LayoutDashboard },
  { name: "Repositories", icon: GitBranch },
  { name: "Pipelines", icon: Workflow },
  { name: "Services & deployments", icon: Layers },
  { name: "Runtime events", icon: Radio },
  { name: "Incidents", icon: ShieldCheck },
  { name: "AI Analyst", icon: Sparkles },
  { name: "Settings", icon: Settings },
];
const descriptions: Record<string, string> = {
  Overview: "The story between your code and what runs in production.",
  Repositories:
    "Changes, findings, and build health across your connected code.",
  Pipelines:
    "Build health is operational evidence. A failed test is not a security incident.",
  "Services & deployments":
    "Know exactly which commit and artifact runs in each environment.",
  "Runtime events":
    "Observed behavior, connected to the deployment active at that time.",
  Incidents: "Investigate relationships with evidence—not assumptions.",
  "AI Analyst":
    "Ask about stored evidence. Every answer stays grounded in your investigation.",
  Settings:
    "A local workspace, read-only GitHub collection, and human-led decisions.",
};
export function Workspace() {
  const [section, setSection] = useState("Overview");
  const [data, setData] = useState<WorkspaceData>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<IncidentDetail>();
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [analystIncident, setAnalystIncident] = useState("");
  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      setData(await api<WorkspaceData>("workspace"));
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }, []);
  useEffect(() => {
    void load();
  }, [load]);
  function navigate(page: string) {
    setSection(page);
    setSelected(undefined);
    setSearch("");
    setNotice("");
    setError("");
  }
  async function open(id: string) {
    setBusy(true);
    setError("");
    try {
      setSelected(await api<IncidentDetail>(`incidents/${id}`));
      setSection("Incidents");
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }
  async function simulate() {
    setBusy(true);
    setError("");
    try {
      const result = await api<{ incident_id: string }>(
        "runtime/events",
        "POST",
        {
          source_event_id: crypto.randomUUID(),
          source: "synthetic",
          service_key: "payments-api",
          asset_key: "pod/payments-api-demo",
          environment: "demo",
          event_type: "network.unusual_outbound",
          severity: "high",
          occurred_at: new Date().toISOString(),
          attributes: {
            destination: "198.51.100.24",
            notice: "Safe synthetic event generated by the demo control",
          },
        },
      );
      await load();
      await open(result.incident_id);
      setNotice(
        "Synthetic event stored and correlated. No external system was contacted.",
      );
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }
  const count =
    data?.incidents.filter(
      (i) => !["Resolved", "False Positive"].includes(i.status),
    ).length || 0;
  const props = data ? { data, search, navigate, open } : undefined;
  return (
    <div className="workspace">
      <aside className="sidebar">
        <a className="brand" href="/">
          <span className="brand-mark">
            <Braces size={23} />
          </span>
          <span>
            BuildBrother <b>AI</b>
            <small>CODE TO CONFIDENCE</small>
          </span>
        </a>
        <div className="workspace-switch">
          <span className="avatar">BB</span>
          <div>
            Founders workspace<small>Local development</small>
          </div>
          <ChevronRight size={14} />
        </div>
        <div className="nav-label">WORKSPACE</div>
        <nav aria-label="Main navigation">
          {navigation.map(({ name, icon: Icon }) => (
            <button
              key={name}
              className={`nav-item ${section === name ? "active" : ""}`}
              aria-current={section === name ? "page" : undefined}
              onClick={() => navigate(name)}
            >
              <Icon size={17} />
              {name}
              {name === "Incidents" && count > 0 && (
                <span className="nav-count">{count}</span>
              )}
              {name === "AI Analyst" && <span className="ai-tag">AI</span>}
            </button>
          ))}
        </nav>
        <div className="sidebar-bottom">
          <div className="shield-note">
            <ShieldCheck size={19} />
            <div>
              Observe. Understand.<small>Always human-approved.</small>
            </div>
          </div>
          <div className="member">
            <span className="avatar">BB</span>
            <div>
              Your team<small>BuildBrother AI · v0.2</small>
            </div>
          </div>
        </div>
      </aside>
      <div className="main-shell">
        <header className="topbar">
          <div>
            Workspace <ChevronRight size={13} />
            <strong>{section}</strong>
          </div>
          <div className="top-actions">
            <span className="local-label">
              <i /> LOCAL WORKSPACE
            </span>
            <span className="avatar">BB</span>
          </div>
        </header>
        <main>
          <div className="page-heading">
            <div>
              <div className="eyebrow">YOUR CODE. THE WHOLE STORY.</div>
              <h1>
                {selected
                  ? "Incident investigation"
                  : section === "Overview"
                    ? "Engineering, with context."
                    : section}
              </h1>
              <p>{descriptions[section]}</p>
            </div>
            <div className="heading-actions">
              <Button variant="outline" onClick={load} disabled={loading}>
                <RefreshCw size={14} className={loading ? "spin" : ""} />
                Refresh
              </Button>
              {data?.services.some(
                (s) => s.key === "payments-api" && s.is_demo,
              ) && (
                <Button
                  onClick={simulate}
                  disabled={busy || !data.settings.ingestion_configured}
                >
                  <Radio size={15} />
                  Simulate event
                </Button>
              )}
            </div>
          </div>
          {data?.settings.demo_mode && (
            <div className="demo-banner">
              <span className="demo-label">
                <i /> DEMO WORKSPACE
              </span>
              <p>
                Explore a safe, synthetic investigation. Demo records are
                labeled and separate from collected GitHub data.
              </p>
              <span>Synthetic runtime data</span>
            </div>
          )}
          {error && (
            <div role="alert" className="message error">
              <CircleAlert size={17} />
              {error}
              <button aria-label="Dismiss error" onClick={() => setError("")}>
                <X size={15} />
              </button>
            </div>
          )}
          {notice && (
            <div role="status" className="message">
              <Check size={17} />
              {notice}
              <button
                aria-label="Dismiss notification"
                onClick={() => setNotice("")}
              >
                <X size={15} />
              </button>
            </div>
          )}
          {!data ? (
            <div className="panel empty-state">
              {loading ? (
                <>
                  <LoaderCircle className="spin" />
                  <p>Connecting to your workspace…</p>
                </>
              ) : (
                <>
                  <Network />
                  <h2>Connect the BuildBrother API</h2>
                  <p>
                    Run the database migrations, then start the backend. Use
                    Refresh to try again.
                  </p>
                </>
              )}
            </div>
          ) : (
            <>
              {section === "Overview" && (
                <Overview data={data} navigate={navigate} open={open} />
              )}
              {[
                "Repositories",
                "Pipelines",
                "Services & deployments",
                "Runtime events",
                "Incidents",
              ].includes(section) &&
                !selected && (
                  <div className="filter-bar">
                    <div className="search">
                      <Search size={16} />
                      <input
                        aria-label={`Search ${section}`}
                        placeholder={`Search ${section.toLowerCase()}…`}
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                      />
                      {search && (
                        <button
                          aria-label="Clear search"
                          onClick={() => setSearch("")}
                        >
                          <X size={14} />
                        </button>
                      )}
                    </div>
                    <span>
                      Stored evidence · up to {data.settings.limit} records per
                      category
                    </span>
                  </div>
                )}
              {section === "Repositories" && props && (
                <Repositories {...props} />
              )}
              {section === "Pipelines" && props && <Pipelines {...props} />}
              {section === "Services & deployments" && props && (
                <Services {...props} />
              )}
              {section === "Runtime events" && props && <Runtime {...props} />}
              {section === "Incidents" && !selected && (
                <section className="panel">
                  <IncidentTable
                    items={data.incidents.filter((i) =>
                      JSON.stringify(i)
                        .toLowerCase()
                        .includes(search.toLowerCase()),
                    )}
                    open={open}
                  />
                </section>
              )}
              {section === "Incidents" && selected && (
                <Investigation
                  key={selected.id}
                  detail={selected}
                  canWrite={data.settings.ingestion_configured}
                  back={() => setSelected(undefined)}
                  onUpdate={(value) => {
                    setSelected(value);
                    void load();
                    setNotice(
                      "Investigation updated. An audit note was saved.",
                    );
                  }}
                  discuss={() => {
                    setAnalystIncident(selected.id);
                    setSelected(undefined);
                    setSection("AI Analyst");
                  }}
                  onError={setError}
                />
              )}
              {section === "AI Analyst" && (
                <Analyst
                  incidents={data.incidents}
                  initialIncident={analystIncident}
                  onError={setError}
                />
              )}
              {section === "Settings" && <WorkspaceSettings data={data} />}
            </>
          )}
          <footer>
            <span>
              <Braces size={14} /> BuildBrother AI
            </span>
            <span>From build to behavior. Evidence all the way.</span>
            <small>LOCAL MVP · HUMAN-LED INVESTIGATION</small>
          </footer>
        </main>
      </div>
    </div>
  );
}
