"""Create BuildBrother provenance and investigation schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql
revision = '56b779327f8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_cursors',
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('etag', sa.String(length=200), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('cached_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('repositories',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('services',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('environment', sa.String(length=60), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('raw_source_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('repository_id', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_event_id', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_event_id', 'kind', 'repository_id')
    )
    op.create_index(op.f('ix_raw_source_events_kind'), 'raw_source_events', ['kind'], unique=False)
    op.create_index(op.f('ix_raw_source_events_repository_id'), 'raw_source_events', ['repository_id'], unique=False)
    op.create_table('repository_services',
    sa.Column('repository_id', sa.String(length=80), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['service_key'], ['services.key'], ),
    sa.PrimaryKeyConstraint('repository_id', 'service_key')
    )
    op.create_table('runtime_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_event_id', sa.String(length=150), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=False),
    sa.Column('asset_key', sa.String(length=200), nullable=False),
    sa.Column('environment', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['service_key'], ['services.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_event_id')
    )
    op.create_index(op.f('ix_runtime_events_occurred_at'), 'runtime_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_runtime_events_service_key'), 'runtime_events', ['service_key'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('repository_id', sa.String(length=80), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('changed_paths', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['raw_source_events.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'sha')
    )
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('repository_id', sa.String(length=80), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('merge_sha', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('changed_paths', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['raw_source_events.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_findings',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('repository_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('package_name', sa.String(length=200), nullable=True),
    sa.Column('package_version', sa.String(length=100), nullable=True),
    sa.Column('ecosystem', sa.String(length=80), nullable=True),
    sa.Column('behavior', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['raw_source_events.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('repository_id', sa.String(length=80), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('conclusion', sa.String(length=30), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['raw_source_events.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'source_run_id')
    )
    op.create_index(op.f('ix_workflow_runs_head_sha'), 'workflow_runs', ['head_sha'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('source_event_id', sa.String(length=150), nullable=False),
    sa.Column('repository_id', sa.String(length=80), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=60), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=80), nullable=True),
    sa.Column('artifact_digest', sa.String(length=80), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['service_key'], ['services.key'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id')
    )
    op.create_index(op.f('ix_deployments_deployed_at'), 'deployments', ['deployed_at'], unique=False)
    op.create_index(op.f('ix_deployments_service_key'), 'deployments', ['service_key'], unique=False)
    op.create_table('workflow_jobs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('conclusion', sa.String(length=30), nullable=True),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['raw_source_events.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_components',
    sa.Column('deployment_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('ecosystem', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('deployment_id', 'name', 'version', 'ecosystem')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('runtime_event_id', sa.String(length=80), nullable=False),
    sa.Column('deployment_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contributions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['runtime_event_id'], ['runtime_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_event_id')
    )
    op.create_table('incident_evidence',
    sa.Column('incident_id', sa.String(length=80), nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('relationship', sa.String(length=200), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'evidence_id')
    )
    op.create_table('incident_notes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('incident_id', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_notes')
    op.drop_table('incident_evidence')
    op.drop_table('incidents')
    op.drop_table('deployment_components')
    op.drop_table('workflow_jobs')
    op.drop_index(op.f('ix_deployments_service_key'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_deployed_at'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_workflow_runs_head_sha'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('security_findings')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_runtime_events_service_key'), table_name='runtime_events')
    op.drop_index(op.f('ix_runtime_events_occurred_at'), table_name='runtime_events')
    op.drop_table('runtime_events')
    op.drop_table('repository_services')
    op.drop_index(op.f('ix_raw_source_events_repository_id'), table_name='raw_source_events')
    op.drop_index(op.f('ix_raw_source_events_kind'), table_name='raw_source_events')
    op.drop_table('raw_source_events')
    op.drop_table('services')
    op.drop_table('repositories')
    op.drop_table('collector_cursors')
    # ### end Alembic commands ###
